FROM node:22.13

# Установка зависимостей для bcrypt
# RUN apk add --no-cache python3 make g++

WORKDIR /app

# Копирование package.json и package-lock.json
COPY package*.json ./

# Установка всех зависимостей, включая devDependencies
RUN npm install

# Копирование исходного кода
COPY . .

# Запуск приложения в режиме разработки
CMD ["npm", "run", "start:dev"]